services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j_container
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4JLABS_PLUGINS=["apoc"]
    ports:
      - "7474:7474"  # Interfaz web de Neo4j
      - "7687:7687"  # Bolt para conexiones
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./import:/var/lib/neo4j/import
      - ./plugins:/plugins
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "RETURN 1"]
      interval: 10s
      retries: 5
      start_period: 30s

  neo4j-loader:
    build: ./scripts
    depends_on:
      neo4j:
        condition: service_healthy

  langchain-api:
    build: ./langchain
    depends_on:
      neo4j:
        condition: service_healthy
      neo4j-loader:
        condition: service_completed_successfully
    volumes:
      - ./langchain:/app
    ports:
      - "5000:5000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password

  streamlit:
    build: ./streamlit
    ports:
      - "8501:8501"
    depends_on:
      - langchain-api
    volumes:
      - ./streamlit:/app
